spring:
  application:
    name: delivery

  # 파일용량 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wowbd

    # DB
    username: root
    password: 1234

# Hibernate
  jpa:
    hibernate:
      ddl-auto: create

# JPA
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: '1234'

session:
  store-type: redis
  redis:
    namespace: shboard:session